using System;

namespace Modio.Errors
{
	public enum FilesystemErrorCode : long
	{
		NONE,
		UNKNOWN = -2147483648L,
		UNABLE_TO_CREATE_FOLDER = -2147483616L,
		UNABLE_TO_CREATE_FILE,
		INSUFFICIENT_SPACE = 20442L,
		NO_PERMISSION = -2147483614L,
		FILE_LOCKED,
		FILE_NOT_FOUND,
		DIRECTORY_NOT_EMPTY,
		READ_ERROR,
		WRITE_ERROR,
		DIRECTORY_NOT_FOUND
	}
}
