using System;

namespace Modio.Errors
{
	public enum GenericErrorCode : long
	{
		NONE,
		UNKNOWN = -2147483648L,
		OPERATION_CANCELLED = -2147483598L,
		OPERATION_ERROR,
		COULD_NOT_CREATE_HANDLE,
		NO_DATA_AVAILABLE,
		END_OF_FILE,
		QUEUE_CLOSED,
		SDKALREADY_INITIALIZED,
		SDKNOT_INITIALIZED,
		INDEX_OUT_OF_RANGE,
		BAD_PARAMETER,
		SHUTTING_DOWN,
		MISSING_COMPONENTS
	}
}
