using System;

namespace Modio.Errors
{
	public enum HttpErrorCode : long
	{
		NONE,
		UNKNOWN = -2147483648L,
		HTTP_NOT_INITIALIZED = -2147483630L,
		HTTP_ALREADY_INITIALIZED,
		CANNOT_OPEN_CONNECTION,
		INSUFFICIENT_PERMISSIONS,
		SECURITY_CONFIGURATION_INVALID,
		SERVER_UNAVAILABLE,
		RESOURCE_NOT_AVAILABLE,
		EXCESSIVE_REDIRECTS,
		SERVER_CLOSED_CONNECTION,
		DOWNLOAD_NOT_PERMITTED,
		SERVERS_OVERLOADED,
		REQUEST_ERROR,
		INVALID_RESPONSE,
		RATE_LIMITED
	}
}
