using System;

namespace Modio.Errors
{
	public enum ModManagementErrorCode : long
	{
		NONE,
		UNKNOWN = -2147483648L,
		ALREADY_SUBSCRIBED = 15004L,
		NO_PENDING_WORK = -2147483571L,
		INSTALL_OR_UPDATE_CANCELLED,
		MOD_MANAGEMENT_DISABLED,
		MOD_MANAGEMENT_ALREADY_ENABLED,
		UPLOAD_CANCELLED,
		MOD_BEING_PROCESSED,
		TEMP_MOD_SET_NOT_INITIALIZED,
		INCOMPATIBLE_DEPENDENCIES
	}
}
