using System;

namespace Modio.Errors
{
	public enum MonetizationErrorCode : long
	{
		NONE,
		UNKNOWN = -2147483648L,
		DISPLAY_PRICE_INCORRECT = -2147483560L,
		MONETIZATION_AUTHENTICATION_FAILED,
		WALLET_FETCH_FAILED,
		USER_MONETIZATION_NOT_CONFIGURED = 900007L,
		USER_MONETIZATION_DISABLED = 900015L,
		GAME_MONETIZATION_NOT_ENABLED = -2147483557L,
		PAYMENT_FAILED,
		INCORRECT_DISPLAY_PRICE,
		ITEM_ALREADY_OWNED,
		INSUFFICIENT_FUNDS,
		RETRY_ENTITLEMENTS
	}
}
