using System;

namespace Modio.Errors
{
	public enum UserAuthErrorCode : long
	{
		NONE,
		UNKNOWN = -2147483648L,
		UNABLE_TO_INIT_STORAGE = -2147483607L,
		STATUS_AUTH_TOKEN_MISSING,
		STATUS_AUTH_TOKEN_INVALID,
		NO_AUTH_TOKEN,
		ALREADY_AUTHENTICATED,
		EMAIL_LOGIN_CODE_EXPIRED = 11012L,
		EMAIL_LOGIN_CODE_INVALID = 11014L
	}
}
