using System;

namespace Modio.Errors
{
	public enum ZlibErrorCode : long
	{
		NONE,
		UNKNOWN = -2147483648L,
		NEED_BUFFERS = -2147483585L,
		END_OF_STREAM,
		STREAM_ERROR,
		INVALID_BLOCK_TYPE,
		INVALID_STORED_LENGTH,
		TOO_MANY_SYMBOLS,
		INVALID_CODE_LENGTHS,
		INVALID_BIT_LENGTH_REPEAT,
		MISSING_EOB,
		INVALID_LITERAL_LENGTH,
		INVALID_DISTANCE_CODE,
		INVALID_DISTANCE,
		OVER_SUBSCRIBED_LENGTH,
		INCOMPLETE_LENGTH_SET
	}
}
