using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text.RegularExpressions;
using Meta.XR.Util;
using UnityEngine;

[HelpURL("https://developer.oculus.com/documentation/unity/move-face-tracking/")]
[Feature(Feature.FaceTracking)]
public static class OVRCustomFaceExtensions
{
	public static OVRFaceExpressions.FaceExpression[] AutoGenerateMapping(Mesh skinnedMesh, string[] blendShapeNames, OVRFaceExpressions.FaceExpression[] faceExpressions, bool allowDuplicateMapping)
	{
		OVRFaceExpressions.FaceExpression[] array = new OVRFaceExpressions.FaceExpression[skinnedMesh.blendShapeCount];
		HashSet<string>[] array2 = new HashSet<string>[blendShapeNames.Length];
		for (int i = 0; i < blendShapeNames.Length; i++)
		{
			array2[i] = OVRCustomFaceExtensions.TokenizeString(blendShapeNames[i]);
		}
		HashSet<OVRFaceExpressions.FaceExpression> hashSet = new HashSet<OVRFaceExpressions.FaceExpression>();
		for (int j = 0; j < skinnedMesh.blendShapeCount; j++)
		{
			string blendShapeName = skinnedMesh.GetBlendShapeName(j);
			OVRFaceExpressions.FaceExpression faceExpression = OVRCustomFaceExtensions.FindBestMatch(array2, blendShapeName, faceExpressions, OVRFaceExpressions.FaceExpression.Invalid);
			if (!allowDuplicateMapping && hashSet.Contains(faceExpression) && !OVRCustomFaceExtensions.IsLipsToward(blendShapeName))
			{
				array[j] = OVRFaceExpressions.FaceExpression.Invalid;
			}
			else
			{
				array[j] = faceExpression;
				hashSet.Add(faceExpression);
			}
		}
		return array;
	}

	private static OVRFaceExpressions.FaceExpression FindBestMatch(HashSet<string>[] tokenizedOptions, string searchString, OVRFaceExpressions.FaceExpression[] expressions, OVRFaceExpressions.FaceExpression fallback)
	{
		searchString = searchString.Substring(searchString.LastIndexOf('.') + 1);
		HashSet<string> first = OVRCustomFaceExtensions.TokenizeString(searchString);
		OVRFaceExpressions.FaceExpression result = fallback;
		int num = 2;
		for (int i = 0; i < tokenizedOptions.Length; i++)
		{
			int num2 = 0;
			HashSet<string> second = tokenizedOptions[i];
			foreach (string text in first.Intersect(second))
			{
				num2 += text.Length;
			}
			if (num2 > num)
			{
				num = num2;
				result = expressions[i];
			}
		}
		return result;
	}

	private static bool IsLipsToward(string blendshapeName)
	{
		blendshapeName = blendshapeName.Substring(blendshapeName.IndexOf('.') + 1);
		return blendshapeName == "lipsToward_LB" || blendshapeName == "lipsToward_RB" || blendshapeName == "lipsToward_LT" || blendshapeName == "lipsToward_RT";
	}

	internal static HashSet<string> TokenizeString(string s)
	{
		char[] separator = new char[]
		{
			' ',
			'_',
			'-',
			',',
			'.',
			';'
		};
		IEnumerable<string> enumerable = OVRCustomFaceExtensions.SplitCamelCase(s).Split(separator).Concat(s.Split(separator));
		HashSet<string> hashSet = new HashSet<string>();
		foreach (string text in enumerable)
		{
			string text2 = text.ToLowerInvariant();
			if (text2 == "left" || text2 == "l")
			{
				hashSet.Add("L");
			}
			if (text2 == "right" || text2 == "r")
			{
				hashSet.Add("R");
			}
			hashSet.Add(text2);
		}
		return hashSet;
	}

	private static string SplitCamelCase(string input)
	{
		return Regex.Replace(input, "([A-Z])", " $1", RegexOptions.Compiled).Trim();
	}

	public static void AutoMapBlendshapes(this OVRCustomFace customFace)
	{
		OVRCustomFace.RetargetingType retargetingType = customFace.retargetingType;
		SkinnedMeshRenderer component = customFace.GetComponent<SkinnedMeshRenderer>();
		try
		{
			OVRFaceExpressions.FaceExpression[] array;
			if (retargetingType != OVRCustomFace.RetargetingType.OculusFace)
			{
				if (retargetingType != OVRCustomFace.RetargetingType.Custom)
				{
					throw new InvalidEnumArgumentException("Invalid RetargetingType");
				}
				array = OVRCustomFaceExtensions.CustomAutoGeneratedMapping(customFace, component.sharedMesh, customFace._allowDuplicateMapping);
			}
			else
			{
				array = OVRCustomFaceExtensions.OculusFaceAutoGenerateMapping(component.sharedMesh, customFace._allowDuplicateMapping);
			}
			if (array != null)
			{
				if (customFace._mappings == null || customFace._mappings.Length != component.sharedMesh.blendShapeCount)
				{
					customFace._mappings = new OVRFaceExpressions.FaceExpression[component.sharedMesh.blendShapeCount];
				}
				for (int i = 0; i < component.sharedMesh.blendShapeCount; i++)
				{
					customFace._mappings[i] = array[i];
				}
			}
		}
		catch (Exception ex)
		{
			Debug.LogError("Auto Map Face Error: " + ex.Message);
		}
	}

	public static void ClearBlendshapes(this OVRCustomFace customFace)
	{
		SkinnedMeshRenderer component = customFace.GetComponent<SkinnedMeshRenderer>();
		for (int i = 0; i < component.sharedMesh.blendShapeCount; i++)
		{
			customFace._mappings[i] = OVRFaceExpressions.FaceExpression.Invalid;
		}
	}

	internal static OVRFaceExpressions.FaceExpression[] OculusFaceAutoGenerateMapping(Mesh sharedMesh, bool allowDuplicateMapping)
	{
		string[] names = Enum.GetNames(typeof(OVRFaceExpressions.FaceExpression));
		OVRFaceExpressions.FaceExpression[] faceExpressions = (OVRFaceExpressions.FaceExpression[])Enum.GetValues(typeof(OVRFaceExpressions.FaceExpression));
		return OVRCustomFaceExtensions.AutoGenerateMapping(sharedMesh, names, faceExpressions, allowDuplicateMapping);
	}

	internal static OVRFaceExpressions.FaceExpression[] CustomAutoGeneratedMapping(OVRCustomFace customFace, Mesh sharedMesh, bool allowDuplicateMapping)
	{
		ValueTuple<string[], OVRFaceExpressions.FaceExpression[]> customBlendShapeNameAndExpressionPairs = customFace.GetCustomBlendShapeNameAndExpressionPairs();
		string[] item = customBlendShapeNameAndExpressionPairs.Item1;
		OVRFaceExpressions.FaceExpression[] item2 = customBlendShapeNameAndExpressionPairs.Item2;
		return OVRCustomFaceExtensions.AutoGenerateMapping(sharedMesh, item, item2, allowDuplicateMapping);
	}
}
