using System;

namespace GT_CustomMapSupportRuntime
{
	public enum SurfaceSoundOverride
	{
		Default,
		None,
		pillowhandtap = 3,
		grassrockhandtap = 7,
		barkhandtap,
		woodhandtap,
		dirthandtap = 14,
		metalhandtap = 18,
		crystalhandtap = 20,
		leafcrunch = 31,
		snowstep,
		crystalhandtap_root_2octdown = 40,
		crystalhandtap_second_2octdown,
		crystalhandtap_third_2octdown,
		crystalhandtap_fifth_2octdown,
		crystalhandtap_sixth_2octdown,
		crystalhandtap_root_1octdown,
		crystalhandtap_second_1octdown,
		crystalhandtap_third_1octdown,
		crystalhandtap_fifth_1octdown,
		crystalhandtap_sixth_1octdown,
		crystalhandtap_root,
		crystalhandtap_root_second,
		crystalhandtap_third,
		crystalhandtap_fifth,
		crystalhandtap_sixth,
		umbrellaopen = 64,
		umbrellaclose,
		keyboardclick,
		buttonpress,
		p2_racktom,
		p1_snare,
		p2_floor_tom_2,
		p2_kick,
		p1_open_hat,
		bongolowest,
		bongohigh,
		squeak_squeeze,
		squeak_release,
		bonerattle,
		Tombstone_Surface_04,
		cauldroninner,
		Cauldron_Surface_04,
		pumpkinhit,
		Web_Surface_02,
		ShortTurkeyGobbleBQuiet,
		foodpop,
		bite1,
		bite2,
		bite3,
		HayImpactA,
		ropecreak,
		planthit,
		ToyFrogSound,
		VineHit1,
		cloud2,
		woodfloor2,
		tire,
		fruitsquish_1,
		washingmachinehit = 98,
		LeafHit1,
		skyjunglewood2,
		skyjunglewood,
		huthit = 105,
		fireflyjarhit,
		beanbag1,
		beanbag2,
		softhit1 = 110,
		storewoodhit = 112,
		shelfhit = 114,
		roofhit,
		cranehit,
		rughit1 = 118,
		snowglobehit = 120,
		ornamenthit,
		gifthit = 134,
		ToyGorillaElf_Squeeze = 140,
		ToyGorillaElf_Release,
		metalhit1 = 146,
		metalhit2 = 149,
		PenguinSqueeze = 154,
		PenguinRelease,
		WolfSqueeze,
		WolfRelease,
		BoxHit = 160,
		DungeonPillowHit = 164,
		BasementWoodWall = 173,
		BookHit = 178,
		MonkeyeSqueeze = 187,
		DragonSqueeze,
		ConcreteHit,
		BeeSqueeze = 191,
		SpongeSquish = 193,
		SpongeRelease_CC0_234872__mlsulli__sponge_being_squeezed_01,
		CoyoteHowl_Quiet2,
		DivingBoardBounce,
		SandTap,
		PalmTreeBark,
		SharkSqueeze = 200,
		SharkRelease,
		TentBounce,
		FireworkMortarInteraction_01__442359__toddcircle__metallic_slap,
		WaterBalloonGrab_04,
		SlipAndSlideStep,
		DolphinSqueeze3,
		DolphinRelease3,
		BugSprayShort,
		Trampoline1 = 210,
		ButtonSplitDownQuiet,
		ButtonSplitUpQuiet,
		HugeCrystalHit,
		crystalhandtap_seventh,
		crystalhandtap_seventh_1octup,
		crystalhandtap_seventh_1octdown,
		crystalhandtap_seventh_2octdown,
		crystalhandtap_fourth,
		crystalhandtap_fourth_1octdown,
		crystalhandtap_fourth_1octup,
		crystalhandtap_fourth_2octdown,
		EelSqueeze,
		EelRelease,
		crystalhandtap_root_1octup,
		crystalhandtap_second_1octup,
		crystalhandtap_third_1octup,
		crystalhandtap_fifth_1octup,
		crystalhandtap_sixth_1octup,
		BottleSqueeze,
		LavaRockBucketGrab_01 = 231,
		sfx_phoenix_caw_fiery_short,
		sfx_fan_open,
		sfx_fan_close,
		CatSqueeze,
		CatRelease,
		Squirrel_Squeezy_Toy_01_SFX,
		Turkey_Baster_Cosmetic_01_SFX,
		Turkey_Baster_Cosmetic_02_SFX,
		SFX_Tin_Soldier_Monke_Toy_001 = 242,
		SFX_Tin_Soldier_Monke_Toy_002,
		GT_Tuning_Fork_001,
		GT_Tuning_Fork_002,
		GT_Tuning_Fork_Fail_006,
		GT_Tuning_Fork_deepring,
		GT_Tuning_Fork_neutralring,
		HeartSqueeze = 250,
		HeartBeat1,
		Smoker_Bellows_Out_short01 = 253,
		Smoker_Bellows_In_short02,
		Race_Bell,
		hand_tap_bounce_house_001,
		hand_tap_bounce_house_002,
		Purple_Step_01,
		GT_Gate_Fence_Closing_End
	}
}
