using System;
using System.Buffers;
using UnityEngine;

namespace Oculus.Interaction
{
	public class GrabFreePhysicsTransformer : MonoBehaviour, ITransformer
	{
		public float VelocityFactor
		{
			get
			{
				return this._velocityFactor;
			}
			set
			{
				this._velocityFactor = value;
			}
		}

		public float AngularVelocityFactor
		{
			get
			{
				return this._angularVelocityFactor;
			}
			set
			{
				this._angularVelocityFactor = value;
			}
		}

		public float MaxLinearDelta
		{
			get
			{
				return this._maxLinearDelta;
			}
			set
			{
				this._maxLinearDelta = value;
			}
		}

		public float MaxAngularDelta
		{
			get
			{
				return this._maxAngularDelta;
			}
			set
			{
				this._maxAngularDelta = value;
			}
		}

		protected virtual void Reset()
		{
			this._rigidbody = base.GetComponent<Rigidbody>();
		}

		public void Initialize(IGrabbable grabbable)
		{
			this._grabbable = grabbable;
			if (this._rigidbody == null)
			{
				this._rigidbody = this._grabbable.Transform.GetComponent<Rigidbody>();
			}
		}

		public void BeginTransform()
		{
			int count = this._grabbable.GrabPoints.Count;
			this._deltas = ArrayPool<GrabFreeTransformer.GrabPointDelta>.Shared.Rent(count);
			GrabFreeTransformer.InitializeDeltas(count, this._grabbable.GrabPoints, ref this._deltas);
			Vector3 centroid = GrabFreeTransformer.GetCentroid(this._grabbable.GrabPoints);
			Transform transform = this._grabbable.Transform;
			this._grabDeltaInLocalSpace = new Pose(transform.InverseTransformVector(centroid - transform.position), transform.rotation);
			this._lastRotation = Quaternion.identity;
			this._targetRotation = this._rigidbody.rotation;
			this._targetPosition = this._rigidbody.position;
			this._isTransforming = true;
		}

		public void UpdateTransform()
		{
			if (!this._isTransforming)
			{
				return;
			}
			int count = this._grabbable.GrabPoints.Count;
			Transform transform = this._grabbable.Transform;
			Vector3 a = GrabFreeTransformer.UpdateTransformerPointData(this._grabbable.GrabPoints, ref this._deltas);
			this._lastRotation = GrabFreeTransformer.UpdateRotation(count, this._deltas) * this._lastRotation;
			this._targetRotation = this._lastRotation * this._grabDeltaInLocalSpace.rotation;
			this._targetPosition = a - transform.TransformVector(this._grabDeltaInLocalSpace.position);
		}

		public void EndTransform()
		{
			this._isTransforming = false;
			ArrayPool<GrabFreeTransformer.GrabPointDelta>.Shared.Return(this._deltas, false);
			this._deltas = null;
		}

		private void FixedUpdate()
		{
			if (this._isTransforming)
			{
				this.ApplyVelocity(this._targetPosition, this._targetRotation);
			}
		}

		private void ApplyVelocity(Vector3 targetPosition, Quaternion targetRotation)
		{
			Vector3 vector = (targetPosition - this._rigidbody.transform.position) * this._velocityFactor;
			if (!float.IsNaN(vector.x))
			{
				this._rigidbody.velocity = Vector3.MoveTowards(this._rigidbody.velocity, vector, this._maxLinearDelta);
			}
			float num;
			Vector3 a;
			(targetRotation * Quaternion.Inverse(this._rigidbody.transform.rotation)).ToAngleAxis(out num, out a);
			if (num > 180f)
			{
				num -= 360f;
			}
			Vector3 vector2 = num * a * this._angularVelocityFactor;
			if (!Mathf.Approximately(num, 0f) && !float.IsNaN(vector2.x))
			{
				this._rigidbody.angularVelocity = Vector3.MoveTowards(this._rigidbody.angularVelocity, vector2, this._maxAngularDelta);
			}
		}

		public void InjectOptionalRigidbody(Rigidbody rigidbody)
		{
			this._rigidbody = rigidbody;
		}

		[Tooltip("Strength of the velocity applied during fixed update")]
		[SerializeField]
		private float _velocityFactor = 60f;

		[Tooltip("Strength of the angular velocity applied during fixed update")]
		[SerializeField]
		private float _angularVelocityFactor = 0.6f;

		[Tooltip("Maximum delta for the linear velocity applied during fixed update")]
		[SerializeField]
		private float _maxLinearDelta = 100f;

		[Tooltip("Maximum delta for the angular velocity applied during fixed update")]
		[SerializeField]
		private float _maxAngularDelta = 200f;

		[SerializeField]
		[Optional(OptionalAttribute.Flag.AutoGenerated)]
		[Tooltip("Rigidbody to which the velocity will be applied.")]
		private Rigidbody _rigidbody;

		private IGrabbable _grabbable;

		private Pose _grabDeltaInLocalSpace;

		private Quaternion _lastRotation = Quaternion.identity;

		private GrabFreeTransformer.GrabPointDelta[] _deltas;

		private bool _isTransforming;

		private Vector3 _targetPosition;

		private Quaternion _targetRotation;
	}
}
