using System;
using UnityEngine;

namespace Oculus.Interaction
{
	public class OptionalAttribute : PropertyAttribute
	{
		public OptionalAttribute.Flag Flags { get; private set; }

		public OptionalAttribute()
		{
		}

		public OptionalAttribute(OptionalAttribute.Flag flags)
		{
			this.Flags = flags;
		}

		[Flags]
		public enum Flag
		{
			None = 0,
			AutoGenerated = 1,
			DontHide = 2,
			Obsolete = 4
		}
	}
}
