using System;

namespace UnityEngine.XR.OpenXR.NativeTypes
{
	public enum XrStructureType : uint
	{
		XR_TYPE_UNKNOWN,
		XR_TYPE_SWAPCHAIN_CREATE_INFO = 9U,
		XR_TYPE_COMPOSITION_LAYER_PROJECTION = 35U,
		XR_TYPE_COMPOSITION_LAYER_QUAD,
		XR_TYPE_COMPOSITION_LAYER_PROJECTION_VIEW = 48U,
		XR_TYPE_COMPOSITION_LAYER_CUBE_KHR = 1000006000U,
		XR_TYPE_COMPOSITION_LAYER_CYLINDER_KHR = 1000017000U,
		XR_TYPE_COMPOSITION_LAYER_EQUIRECT_KHR = 1000018000U,
		XR_TYPE_COMPOSITION_LAYER_EQUIRECT2_KHR = 1000091000U
	}
}
