using System;

namespace UnityEngine.XR.OpenXR.NativeTypes
{
	[Flags]
	public enum XrSwapchainUsageFlags : ulong
	{
		XR_SWAPCHAIN_USAGE_COLOR_ATTACHMENT_BIT = 1UL,
		XR_SWAPCHAIN_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT = 2UL,
		XR_SWAPCHAIN_USAGE_UNORDERED_ACCESS_BIT = 4UL,
		XR_SWAPCHAIN_USAGE_TRANSFER_SRC_BIT = 8UL,
		XR_SWAPCHAIN_USAGE_TRANSFER_DST_BIT = 16UL,
		XR_SWAPCHAIN_USAGE_SAMPLED_BIT = 32UL,
		XR_SWAPCHAIN_USAGE_MUTABLE_FORMAT_BIT = 64UL,
		XR_SWAPCHAIN_USAGE_INPUT_ATTACHMENT_BIT_MND = 128UL,
		XR_SWAPCHAIN_USAGE_INPUT_ATTACHMENT_BIT_KHR = 128UL
	}
}
