using System;

namespace OVR.OpenVR
{
	public enum ETrackedDeviceProperty
	{
		Prop_Invalid,
		Prop_TrackingSystemName_String = 1000,
		Prop_ModelNumber_String,
		Prop_SerialNumber_String,
		Prop_RenderModelName_String,
		Prop_WillDriftInYaw_Bool,
		Prop_ManufacturerName_String,
		Prop_TrackingFirmwareVersion_String,
		Prop_HardwareRevision_String,
		Prop_AllWirelessDongleDescriptions_String,
		Prop_ConnectedWirelessDongle_String,
		Prop_DeviceIsWireless_Bool,
		Prop_DeviceIsCharging_Bool,
		Prop_DeviceBatteryPercentage_Float,
		Prop_StatusDisplayTransform_Matrix34,
		Prop_Firmware_UpdateAvailable_Bool,
		Prop_Firmware_ManualUpdate_Bool,
		Prop_Firmware_ManualUpdateURL_String,
		Prop_HardwareRevision_Uint64,
		Prop_FirmwareVersion_Uint64,
		Prop_FPGAVersion_Uint64,
		Prop_VRCVersion_Uint64,
		Prop_RadioVersion_Uint64,
		Prop_DongleVersion_Uint64,
		Prop_BlockServerShutdown_Bool,
		Prop_CanUnifyCoordinateSystemWithHmd_Bool,
		Prop_ContainsProximitySensor_Bool,
		Prop_DeviceProvidesBatteryStatus_Bool,
		Prop_DeviceCanPowerOff_Bool,
		Prop_Firmware_ProgrammingTarget_String,
		Prop_DeviceClass_Int32,
		Prop_HasCamera_Bool,
		Prop_DriverVersion_String,
		Prop_Firmware_ForceUpdateRequired_Bool,
		Prop_ViveSystemButtonFixRequired_Bool,
		Prop_ParentDriver_Uint64,
		Prop_ResourceRoot_String,
		Prop_RegisteredDeviceType_String,
		Prop_InputProfilePath_String,
		Prop_NeverTracked_Bool,
		Prop_NumCameras_Int32,
		Prop_CameraFrameLayout_Int32,
		Prop_ReportsTimeSinceVSync_Bool = 2000,
		Prop_SecondsFromVsyncToPhotons_Float,
		Prop_DisplayFrequency_Float,
		Prop_UserIpdMeters_Float,
		Prop_CurrentUniverseId_Uint64,
		Prop_PreviousUniverseId_Uint64,
		Prop_DisplayFirmwareVersion_Uint64,
		Prop_IsOnDesktop_Bool,
		Prop_DisplayMCType_Int32,
		Prop_DisplayMCOffset_Float,
		Prop_DisplayMCScale_Float,
		Prop_EdidVendorID_Int32,
		Prop_DisplayMCImageLeft_String,
		Prop_DisplayMCImageRight_String,
		Prop_DisplayGCBlackClamp_Float,
		Prop_EdidProductID_Int32,
		Prop_CameraToHeadTransform_Matrix34,
		Prop_DisplayGCType_Int32,
		Prop_DisplayGCOffset_Float,
		Prop_DisplayGCScale_Float,
		Prop_DisplayGCPrescale_Float,
		Prop_DisplayGCImage_String,
		Prop_LensCenterLeftU_Float,
		Prop_LensCenterLeftV_Float,
		Prop_LensCenterRightU_Float,
		Prop_LensCenterRightV_Float,
		Prop_UserHeadToEyeDepthMeters_Float,
		Prop_CameraFirmwareVersion_Uint64,
		Prop_CameraFirmwareDescription_String,
		Prop_DisplayFPGAVersion_Uint64,
		Prop_DisplayBootloaderVersion_Uint64,
		Prop_DisplayHardwareVersion_Uint64,
		Prop_AudioFirmwareVersion_Uint64,
		Prop_CameraCompatibilityMode_Int32,
		Prop_ScreenshotHorizontalFieldOfViewDegrees_Float,
		Prop_ScreenshotVerticalFieldOfViewDegrees_Float,
		Prop_DisplaySuppressed_Bool,
		Prop_DisplayAllowNightMode_Bool,
		Prop_DisplayMCImageWidth_Int32,
		Prop_DisplayMCImageHeight_Int32,
		Prop_DisplayMCImageNumChannels_Int32,
		Prop_DisplayMCImageData_Binary,
		Prop_SecondsFromPhotonsToVblank_Float,
		Prop_DriverDirectModeSendsVsyncEvents_Bool,
		Prop_DisplayDebugMode_Bool,
		Prop_GraphicsAdapterLuid_Uint64,
		Prop_DriverProvidedChaperonePath_String = 2048,
		Prop_ExpectedTrackingReferenceCount_Int32,
		Prop_ExpectedControllerCount_Int32,
		Prop_NamedIconPathControllerLeftDeviceOff_String,
		Prop_NamedIconPathControllerRightDeviceOff_String,
		Prop_NamedIconPathTrackingReferenceDeviceOff_String,
		Prop_DoNotApplyPrediction_Bool,
		Prop_CameraToHeadTransforms_Matrix34_Array,
		Prop_DistortionMeshResolution_Int32,
		Prop_DriverIsDrawingControllers_Bool,
		Prop_DriverRequestsApplicationPause_Bool,
		Prop_DriverRequestsReducedRendering_Bool,
		Prop_MinimumIpdStepMeters_Float,
		Prop_AudioBridgeFirmwareVersion_Uint64,
		Prop_ImageBridgeFirmwareVersion_Uint64,
		Prop_ImuToHeadTransform_Matrix34,
		Prop_ImuFactoryGyroBias_Vector3,
		Prop_ImuFactoryGyroScale_Vector3,
		Prop_ImuFactoryAccelerometerBias_Vector3,
		Prop_ImuFactoryAccelerometerScale_Vector3,
		Prop_ConfigurationIncludesLighthouse20Features_Bool = 2069,
		Prop_DriverRequestedMuraCorrectionMode_Int32 = 2200,
		Prop_DriverRequestedMuraFeather_InnerLeft_Int32,
		Prop_DriverRequestedMuraFeather_InnerRight_Int32,
		Prop_DriverRequestedMuraFeather_InnerTop_Int32,
		Prop_DriverRequestedMuraFeather_InnerBottom_Int32,
		Prop_DriverRequestedMuraFeather_OuterLeft_Int32,
		Prop_DriverRequestedMuraFeather_OuterRight_Int32,
		Prop_DriverRequestedMuraFeather_OuterTop_Int32,
		Prop_DriverRequestedMuraFeather_OuterBottom_Int32,
		Prop_AttachedDeviceId_String = 3000,
		Prop_SupportedButtons_Uint64,
		Prop_Axis0Type_Int32,
		Prop_Axis1Type_Int32,
		Prop_Axis2Type_Int32,
		Prop_Axis3Type_Int32,
		Prop_Axis4Type_Int32,
		Prop_ControllerRoleHint_Int32,
		Prop_FieldOfViewLeftDegrees_Float = 4000,
		Prop_FieldOfViewRightDegrees_Float,
		Prop_FieldOfViewTopDegrees_Float,
		Prop_FieldOfViewBottomDegrees_Float,
		Prop_TrackingRangeMinimumMeters_Float,
		Prop_TrackingRangeMaximumMeters_Float,
		Prop_ModeLabel_String,
		Prop_IconPathName_String = 5000,
		Prop_NamedIconPathDeviceOff_String,
		Prop_NamedIconPathDeviceSearching_String,
		Prop_NamedIconPathDeviceSearchingAlert_String,
		Prop_NamedIconPathDeviceReady_String,
		Prop_NamedIconPathDeviceReadyAlert_String,
		Prop_NamedIconPathDeviceNotReady_String,
		Prop_NamedIconPathDeviceStandby_String,
		Prop_NamedIconPathDeviceAlertLow_String,
		Prop_DisplayHiddenArea_Binary_Start = 5100,
		Prop_DisplayHiddenArea_Binary_End = 5150,
		Prop_ParentContainer,
		Prop_UserConfigPath_String = 6000,
		Prop_InstallPath_String,
		Prop_HasDisplayComponent_Bool,
		Prop_HasControllerComponent_Bool,
		Prop_HasCameraComponent_Bool,
		Prop_HasDriverDirectModeComponent_Bool,
		Prop_HasVirtualDisplayComponent_Bool,
		Prop_HasSpatialAnchorsSupport_Bool,
		Prop_ControllerType_String = 7000,
		Prop_LegacyInputProfile_String,
		Prop_VendorSpecific_Reserved_Start = 10000,
		Prop_VendorSpecific_Reserved_End = 10999,
		Prop_TrackedDeviceProperty_Max = 1000000
	}
}
