using System;

namespace OVR.OpenVR
{
	public enum EVREventType
	{
		VREvent_None,
		VREvent_TrackedDeviceActivated = 100,
		VREvent_TrackedDeviceDeactivated,
		VREvent_TrackedDeviceUpdated,
		VREvent_TrackedDeviceUserInteractionStarted,
		VREvent_TrackedDeviceUserInteractionEnded,
		VREvent_IpdChanged,
		VREvent_EnterStandbyMode,
		VREvent_LeaveStandbyMode,
		VREvent_TrackedDeviceRoleChanged,
		VREvent_WatchdogWakeUpRequested,
		VREvent_LensDistortionChanged,
		VREvent_PropertyChanged,
		VREvent_WirelessDisconnect,
		VREvent_WirelessReconnect,
		VREvent_ButtonPress = 200,
		VREvent_ButtonUnpress,
		VREvent_ButtonTouch,
		VREvent_ButtonUntouch,
		VREvent_DualAnalog_Press = 250,
		VREvent_DualAnalog_Unpress,
		VREvent_DualAnalog_Touch,
		VREvent_DualAnalog_Untouch,
		VREvent_DualAnalog_Move,
		VREvent_DualAnalog_ModeSwitch1,
		VREvent_DualAnalog_ModeSwitch2,
		VREvent_DualAnalog_Cancel,
		VREvent_MouseMove = 300,
		VREvent_MouseButtonDown,
		VREvent_MouseButtonUp,
		VREvent_FocusEnter,
		VREvent_FocusLeave,
		VREvent_Scroll,
		VREvent_TouchPadMove,
		VREvent_OverlayFocusChanged,
		VREvent_InputFocusCaptured = 400,
		VREvent_InputFocusReleased,
		VREvent_SceneFocusLost,
		VREvent_SceneFocusGained,
		VREvent_SceneApplicationChanged,
		VREvent_SceneFocusChanged,
		VREvent_InputFocusChanged,
		VREvent_SceneApplicationSecondaryRenderingStarted,
		VREvent_SceneApplicationUsingWrongGraphicsAdapter,
		VREvent_ActionBindingReloaded,
		VREvent_HideRenderModels,
		VREvent_ShowRenderModels,
		VREvent_ConsoleOpened = 420,
		VREvent_ConsoleClosed,
		VREvent_OverlayShown = 500,
		VREvent_OverlayHidden,
		VREvent_DashboardActivated,
		VREvent_DashboardDeactivated,
		VREvent_DashboardThumbSelected,
		VREvent_DashboardRequested,
		VREvent_ResetDashboard,
		VREvent_RenderToast,
		VREvent_ImageLoaded,
		VREvent_ShowKeyboard,
		VREvent_HideKeyboard,
		VREvent_OverlayGamepadFocusGained,
		VREvent_OverlayGamepadFocusLost,
		VREvent_OverlaySharedTextureChanged,
		VREvent_ScreenshotTriggered = 516,
		VREvent_ImageFailed,
		VREvent_DashboardOverlayCreated,
		VREvent_SwitchGamepadFocus,
		VREvent_RequestScreenshot,
		VREvent_ScreenshotTaken,
		VREvent_ScreenshotFailed,
		VREvent_SubmitScreenshotToDashboard,
		VREvent_ScreenshotProgressToDashboard,
		VREvent_PrimaryDashboardDeviceChanged,
		VREvent_RoomViewShown,
		VREvent_RoomViewHidden,
		VREvent_Notification_Shown = 600,
		VREvent_Notification_Hidden,
		VREvent_Notification_BeginInteraction,
		VREvent_Notification_Destroyed,
		VREvent_Quit = 700,
		VREvent_ProcessQuit,
		VREvent_QuitAborted_UserPrompt,
		VREvent_QuitAcknowledged,
		VREvent_DriverRequestedQuit,
		VREvent_ChaperoneDataHasChanged = 800,
		VREvent_ChaperoneUniverseHasChanged,
		VREvent_ChaperoneTempDataHasChanged,
		VREvent_ChaperoneSettingsHaveChanged,
		VREvent_SeatedZeroPoseReset,
		VREvent_AudioSettingsHaveChanged = 820,
		VREvent_BackgroundSettingHasChanged = 850,
		VREvent_CameraSettingsHaveChanged,
		VREvent_ReprojectionSettingHasChanged,
		VREvent_ModelSkinSettingsHaveChanged,
		VREvent_EnvironmentSettingsHaveChanged,
		VREvent_PowerSettingsHaveChanged,
		VREvent_EnableHomeAppSettingsHaveChanged,
		VREvent_SteamVRSectionSettingChanged,
		VREvent_LighthouseSectionSettingChanged,
		VREvent_NullSectionSettingChanged,
		VREvent_UserInterfaceSectionSettingChanged,
		VREvent_NotificationsSectionSettingChanged,
		VREvent_KeyboardSectionSettingChanged,
		VREvent_PerfSectionSettingChanged,
		VREvent_DashboardSectionSettingChanged,
		VREvent_WebInterfaceSectionSettingChanged,
		VREvent_TrackersSectionSettingChanged,
		VREvent_StatusUpdate = 900,
		VREvent_WebInterface_InstallDriverCompleted = 950,
		VREvent_MCImageUpdated = 1000,
		VREvent_FirmwareUpdateStarted = 1100,
		VREvent_FirmwareUpdateFinished,
		VREvent_KeyboardClosed = 1200,
		VREvent_KeyboardCharInput,
		VREvent_KeyboardDone,
		VREvent_ApplicationTransitionStarted = 1300,
		VREvent_ApplicationTransitionAborted,
		VREvent_ApplicationTransitionNewAppStarted,
		VREvent_ApplicationListUpdated,
		VREvent_ApplicationMimeTypeLoad,
		VREvent_ApplicationTransitionNewAppLaunchComplete,
		VREvent_ProcessConnected,
		VREvent_ProcessDisconnected,
		VREvent_Compositor_MirrorWindowShown = 1400,
		VREvent_Compositor_MirrorWindowHidden,
		VREvent_Compositor_ChaperoneBoundsShown = 1410,
		VREvent_Compositor_ChaperoneBoundsHidden,
		VREvent_TrackedCamera_StartVideoStream = 1500,
		VREvent_TrackedCamera_StopVideoStream,
		VREvent_TrackedCamera_PauseVideoStream,
		VREvent_TrackedCamera_ResumeVideoStream,
		VREvent_TrackedCamera_EditingSurface = 1550,
		VREvent_PerformanceTest_EnableCapture = 1600,
		VREvent_PerformanceTest_DisableCapture,
		VREvent_PerformanceTest_FidelityLevel,
		VREvent_MessageOverlay_Closed = 1650,
		VREvent_MessageOverlayCloseRequested,
		VREvent_Input_HapticVibration = 1700,
		VREvent_Input_BindingLoadFailed,
		VREvent_Input_BindingLoadSuccessful,
		VREvent_Input_ActionManifestReloaded,
		VREvent_Input_ActionManifestLoadFailed,
		VREvent_SpatialAnchors_PoseUpdated = 1800,
		VREvent_SpatialAnchors_DescriptorUpdated,
		VREvent_SpatialAnchors_RequestPoseUpdate,
		VREvent_SpatialAnchors_RequestDescriptorUpdate,
		VREvent_VendorSpecific_Reserved_Start = 10000,
		VREvent_VendorSpecific_Reserved_End = 19999
	}
}
