using System;

namespace OVR.OpenVR
{
	public enum EVRInitError
	{
		None,
		Unknown,
		Init_InstallationNotFound = 100,
		Init_InstallationCorrupt,
		Init_VRClientDLLNotFound,
		Init_FileNotFound,
		Init_FactoryNotFound,
		Init_InterfaceNotFound,
		Init_InvalidInterface,
		Init_UserConfigDirectoryInvalid,
		Init_HmdNotFound,
		Init_NotInitialized,
		Init_PathRegistryNotFound,
		Init_NoConfigPath,
		Init_NoLogPath,
		Init_PathRegistryNotWritable,
		Init_AppInfoInitFailed,
		Init_Retry,
		Init_InitCanceledByUser,
		Init_AnotherAppLaunching,
		Init_SettingsInitFailed,
		Init_ShuttingDown,
		Init_TooManyObjects,
		Init_NoServerForBackgroundApp,
		Init_NotSupportedWithCompositor,
		Init_NotAvailableToUtilityApps,
		Init_Internal,
		Init_HmdDriverIdIsNone,
		Init_HmdNotFoundPresenceFailed,
		Init_VRMonitorNotFound,
		Init_VRMonitorStartupFailed,
		Init_LowPowerWatchdogNotSupported,
		Init_InvalidApplicationType,
		Init_NotAvailableToWatchdogApps,
		Init_WatchdogDisabledInSettings,
		Init_VRDashboardNotFound,
		Init_VRDashboardStartupFailed,
		Init_VRHomeNotFound,
		Init_VRHomeStartupFailed,
		Init_RebootingBusy,
		Init_FirmwareUpdateBusy,
		Init_FirmwareRecoveryBusy,
		Init_USBServiceBusy,
		Init_VRWebHelperStartupFailed,
		Init_TrackerManagerInitFailed,
		Driver_Failed = 200,
		Driver_Unknown,
		Driver_HmdUnknown,
		Driver_NotLoaded,
		Driver_RuntimeOutOfDate,
		Driver_HmdInUse,
		Driver_NotCalibrated,
		Driver_CalibrationInvalid,
		Driver_HmdDisplayNotFound,
		Driver_TrackedDeviceInterfaceUnknown,
		Driver_HmdDriverIdOutOfBounds = 211,
		Driver_HmdDisplayMirrored,
		IPC_ServerInitFailed = 300,
		IPC_ConnectFailed,
		IPC_SharedStateInitFailed,
		IPC_CompositorInitFailed,
		IPC_MutexInitFailed,
		IPC_Failed,
		IPC_CompositorConnectFailed,
		IPC_CompositorInvalidConnectResponse,
		IPC_ConnectFailedAfterMultipleAttempts,
		Compositor_Failed = 400,
		Compositor_D3D11HardwareRequired,
		Compositor_FirmwareRequiresUpdate,
		Compositor_OverlayInitFailed,
		Compositor_ScreenshotsInitFailed,
		Compositor_UnableToCreateDevice,
		VendorSpecific_UnableToConnectToOculusRuntime = 1000,
		VendorSpecific_WindowsNotInDevMode,
		VendorSpecific_HmdFound_CantOpenDevice = 1101,
		VendorSpecific_HmdFound_UnableToRequestConfigStart,
		VendorSpecific_HmdFound_NoStoredConfig,
		VendorSpecific_HmdFound_ConfigTooBig,
		VendorSpecific_HmdFound_ConfigTooSmall,
		VendorSpecific_HmdFound_UnableToInitZLib,
		VendorSpecific_HmdFound_CantReadFirmwareVersion,
		VendorSpecific_HmdFound_UnableToSendUserDataStart,
		VendorSpecific_HmdFound_UnableToGetUserDataStart,
		VendorSpecific_HmdFound_UnableToGetUserDataNext,
		VendorSpecific_HmdFound_UserDataAddressRange,
		VendorSpecific_HmdFound_UserDataError,
		VendorSpecific_HmdFound_ConfigFailedSanityCheck,
		Steam_SteamInstallationNotFound = 2000
	}
}
