using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.Playables;
using UnityEngine.Serialization;

namespace Unity.Cinemachine
{
	[SaveDuringPlay]
	[AddComponentMenu("Cinemachine/Helpers/Cinemachine Trigger Action")]
	[HelpURL("https://docs.unity3d.com/Packages/com.unity.cinemachine@3.1/manual/CinemachineTriggerAction.html")]
	public class CinemachineTriggerAction : MonoBehaviour
	{
		private bool Filter(GameObject other)
		{
			return base.enabled && (1 << other.layer & this.LayerMask) != 0 && (this.WithTag.Length == 0 || other.CompareTag(this.WithTag)) && (this.WithoutTag.Length == 0 || !other.CompareTag(this.WithoutTag));
		}

		private void InternalDoTriggerEnter(GameObject other)
		{
			if (!this.Filter(other))
			{
				return;
			}
			this.SkipFirst--;
			if (this.SkipFirst > -1)
			{
				return;
			}
			if (!this.Repeating && this.SkipFirst != -1)
			{
				return;
			}
			this.m_ActiveTriggerObjects.Add(other);
			this.OnObjectEnter.Invoke();
		}

		private void InternalDoTriggerExit(GameObject other)
		{
			if (!this.m_ActiveTriggerObjects.Contains(other))
			{
				return;
			}
			this.m_ActiveTriggerObjects.Remove(other);
			if (base.enabled)
			{
				this.OnObjectExit.Invoke();
			}
		}

		private void OnTriggerEnter(Collider other)
		{
			this.InternalDoTriggerEnter(other.gameObject);
		}

		private void OnTriggerExit(Collider other)
		{
			this.InternalDoTriggerExit(other.gameObject);
		}

		private void OnCollisionEnter(Collision other)
		{
			this.InternalDoTriggerEnter(other.gameObject);
		}

		private void OnCollisionExit(Collision other)
		{
			this.InternalDoTriggerExit(other.gameObject);
		}

		private void OnTriggerEnter2D(Collider2D other)
		{
			this.InternalDoTriggerEnter(other.gameObject);
		}

		private void OnTriggerExit2D(Collider2D other)
		{
			this.InternalDoTriggerExit(other.gameObject);
		}

		private void OnCollisionEnter2D(Collision2D other)
		{
			this.InternalDoTriggerEnter(other.gameObject);
		}

		private void OnCollisionExit2D(Collision2D other)
		{
			this.InternalDoTriggerExit(other.gameObject);
		}

		private void OnEnable()
		{
		}

		[Header("Trigger Object Filter")]
		[Tooltip("Only triggers generated by objects on these layers will be considered")]
		[FormerlySerializedAs("m_LayerMask")]
		public LayerMask LayerMask = 1;

		[TagField]
		[Tooltip("If set, only triggers generated by objects with this tag will be considered")]
		[FormerlySerializedAs("m_WithTag")]
		public string WithTag = string.Empty;

		[TagField]
		[Tooltip("Triggers generated by objects with this tag will be ignored")]
		[FormerlySerializedAs("m_WithoutTag")]
		public string WithoutTag = string.Empty;

		[NoSaveDuringPlay]
		[Tooltip("Skip this many trigger entries before taking action")]
		[FormerlySerializedAs("m_SkipFirst")]
		public int SkipFirst;

		[Tooltip("Repeat the action for all subsequent trigger entries")]
		[FormerlySerializedAs("m_Repeating")]
		public bool Repeating = true;

		[Tooltip("What action to take when an eligible object enters the collider or trigger zone")]
		[FormerlySerializedAs("m_OnObjectEnter")]
		public CinemachineTriggerAction.ActionSettings OnObjectEnter = new CinemachineTriggerAction.ActionSettings(CinemachineTriggerAction.ActionSettings.ActionModes.EventOnly);

		[Tooltip("What action to take when an eligible object exits the collider or trigger zone")]
		[FormerlySerializedAs("m_OnObjectExit")]
		public CinemachineTriggerAction.ActionSettings OnObjectExit = new CinemachineTriggerAction.ActionSettings(CinemachineTriggerAction.ActionSettings.ActionModes.EventOnly);

		private HashSet<GameObject> m_ActiveTriggerObjects = new HashSet<GameObject>();

		[Serializable]
		public struct ActionSettings
		{
			public ActionSettings(CinemachineTriggerAction.ActionSettings.ActionModes action)
			{
				this.Action = action;
				this.Target = null;
				this.BoostAmount = 0;
				this.StartTime = 0f;
				this.Mode = CinemachineTriggerAction.ActionSettings.TimeModes.FromStart;
				this.Event = new CinemachineTriggerAction.ActionSettings.TriggerEvent();
			}

			public void Invoke()
			{
				Object target = this.Target;
				if (target != null)
				{
					GameObject gameObject = target as GameObject;
					Behaviour behaviour = target as Behaviour;
					if (behaviour != null)
					{
						gameObject = behaviour.gameObject;
					}
					switch (this.Action)
					{
					case CinemachineTriggerAction.ActionSettings.ActionModes.PriorityBoost:
					{
						CinemachineVirtualCameraBase cinemachineVirtualCameraBase;
						if (gameObject.TryGetComponent<CinemachineVirtualCameraBase>(out cinemachineVirtualCameraBase))
						{
							CinemachineVirtualCameraBase cinemachineVirtualCameraBase2 = cinemachineVirtualCameraBase;
							cinemachineVirtualCameraBase2.Priority.Value = cinemachineVirtualCameraBase2.Priority.Value + this.BoostAmount;
							cinemachineVirtualCameraBase.Prioritize();
						}
						break;
					}
					case CinemachineTriggerAction.ActionSettings.ActionModes.Activate:
						if (gameObject != null)
						{
							gameObject.SetActive(true);
							CinemachineVirtualCameraBase cinemachineVirtualCameraBase3;
							if (gameObject.TryGetComponent<CinemachineVirtualCameraBase>(out cinemachineVirtualCameraBase3))
							{
								cinemachineVirtualCameraBase3.Prioritize();
							}
						}
						break;
					case CinemachineTriggerAction.ActionSettings.ActionModes.Deactivate:
						if (gameObject != null)
						{
							gameObject.SetActive(false);
						}
						break;
					case CinemachineTriggerAction.ActionSettings.ActionModes.Enable:
						if (behaviour != null)
						{
							behaviour.enabled = true;
						}
						break;
					case CinemachineTriggerAction.ActionSettings.ActionModes.Disable:
						if (behaviour != null)
						{
							behaviour.enabled = false;
						}
						break;
					case CinemachineTriggerAction.ActionSettings.ActionModes.Play:
					{
						PlayableDirector playableDirector;
						Animation animation;
						if (gameObject.TryGetComponent<PlayableDirector>(out playableDirector))
						{
							double num = 0.0;
							double duration = playableDirector.duration;
							double time = playableDirector.time;
							switch (this.Mode)
							{
							default:
								num += (double)this.StartTime;
								break;
							case CinemachineTriggerAction.ActionSettings.TimeModes.FromEnd:
								num = duration - (double)this.StartTime;
								break;
							case CinemachineTriggerAction.ActionSettings.TimeModes.BeforeNow:
								num = time - (double)this.StartTime;
								break;
							case CinemachineTriggerAction.ActionSettings.TimeModes.AfterNow:
								num = time + (double)this.StartTime;
								break;
							}
							playableDirector.time = num;
							playableDirector.Play();
						}
						else if (gameObject.TryGetComponent<Animation>(out animation))
						{
							animation.Play();
						}
						break;
					}
					case CinemachineTriggerAction.ActionSettings.ActionModes.Stop:
					{
						PlayableDirector playableDirector2;
						Animation animation2;
						if (gameObject.TryGetComponent<PlayableDirector>(out playableDirector2))
						{
							playableDirector2.Stop();
						}
						else if (gameObject.TryGetComponent<Animation>(out animation2))
						{
							animation2.Stop();
						}
						break;
					}
					}
				}
				this.Event.Invoke();
			}

			[Tooltip("What action to take")]
			[FormerlySerializedAs("m_Action")]
			public CinemachineTriggerAction.ActionSettings.ActionModes Action;

			[Tooltip("The target object on which to operate.  If null, then the current behaviour/GameObject will be used")]
			[FormerlySerializedAs("m_Target")]
			public Object Target;

			[Tooltip("If PriorityBoost, this amount will be added to the virtual camera's priority")]
			[FormerlySerializedAs("m_BoostAmount")]
			public int BoostAmount;

			[Tooltip("If playing a timeline, start at this time")]
			[FormerlySerializedAs("m_StartTime")]
			public float StartTime;

			[Tooltip("How to interpret the start time")]
			[FormerlySerializedAs("m_Mode")]
			public CinemachineTriggerAction.ActionSettings.TimeModes Mode;

			[Tooltip("This event will be invoked")]
			[FormerlySerializedAs("m_Event")]
			public CinemachineTriggerAction.ActionSettings.TriggerEvent Event;

			public enum ActionModes
			{
				EventOnly,
				PriorityBoost,
				Activate,
				Deactivate,
				Enable,
				Disable,
				Play,
				Stop
			}

			[Serializable]
			public class TriggerEvent : UnityEvent
			{
			}

			public enum TimeModes
			{
				FromStart,
				FromEnd,
				BeforeNow,
				AfterNow
			}
		}
	}
}
