using System;
using System.Collections.Generic;
using Technie.PhysicsCreator.Rigid;
using UnityEngine;

namespace Technie.PhysicsCreator
{
	public class HullMapping
	{
		public void AddAutoChild(RigidColliderCreatorChild newChild, MeshCollider newCollider)
		{
			if (newChild != null)
			{
				List<RigidColliderCreatorChild> list = new List<RigidColliderCreatorChild>();
				if (this.targetAutoGeneratedChilds != null)
				{
					list.AddRange(this.targetAutoGeneratedChilds);
				}
				if (!list.Contains(newChild))
				{
					list.Add(newChild);
					this.targetAutoGeneratedChilds = list.ToArray();
				}
			}
			if (newCollider != null)
			{
				List<MeshCollider> list2 = new List<MeshCollider>();
				if (this.autoGeneratedColliders != null)
				{
					list2.AddRange(this.autoGeneratedColliders);
				}
				if (!list2.Contains(newCollider))
				{
					list2.Add(newCollider);
					this.autoGeneratedColliders = list2.ToArray();
				}
			}
		}

		public Hull sourceHull;

		public Collider generatedCollider;

		public MeshCollider[] autoGeneratedColliders;

		public RigidColliderCreatorChild targetChild;

		public RigidColliderCreatorChild[] targetAutoGeneratedChilds;
	}
}
