using System;
using System.Collections.Generic;
using Technie.PhysicsCreator.Rigid;
using UnityEngine;

namespace Technie.PhysicsCreator
{
	public class RigidColliderCreator : MonoBehaviour, ICreatorComponent
	{
		private void OnDestroy()
		{
		}

		public GameObject GetGameObject()
		{
			return base.gameObject;
		}

		public bool HasEditorData()
		{
			return this.paintingData != null;
		}

		public IEditorData GetEditorData()
		{
			return this.paintingData;
		}

		public void CreateColliderComponents(Mesh[] autoHulls)
		{
			this.CreateHullMapping();
			foreach (Hull hull in this.paintingData.hulls)
			{
				this.UpdateCollider(hull);
			}
			foreach (Hull hull2 in this.paintingData.hulls)
			{
				this.CreateAutoHulls(hull2, autoHulls);
			}
		}

		public void RemoveAllColliders()
		{
			if (this.hullMapping != null)
			{
				foreach (HullMapping hullMapping in this.hullMapping)
				{
					RigidColliderCreator.DestroyImmediateWithUndo(hullMapping.generatedCollider);
					if (hullMapping.autoGeneratedColliders != null)
					{
						MeshCollider[] autoGeneratedColliders = hullMapping.autoGeneratedColliders;
						for (int i = 0; i < autoGeneratedColliders.Length; i++)
						{
							RigidColliderCreator.DestroyImmediateWithUndo(autoGeneratedColliders[i]);
						}
					}
				}
				for (int j = this.hullMapping.Count - 1; j >= 0; j--)
				{
					if (this.hullMapping[j].targetChild != null)
					{
						this.hullMapping.RemoveAt(j);
					}
				}
			}
		}

		public void RemoveAllGenerated()
		{
			this.CreateHullMapping();
			foreach (HullMapping hullMapping in this.hullMapping)
			{
				RigidColliderCreator.DestroyImmediateWithUndo(hullMapping.generatedCollider);
				if (hullMapping.targetChild != null)
				{
					RigidColliderCreator.DestroyImmediateWithUndo(hullMapping.targetChild.gameObject);
				}
				if (hullMapping.autoGeneratedColliders != null)
				{
					MeshCollider[] autoGeneratedColliders = hullMapping.autoGeneratedColliders;
					for (int i = 0; i < autoGeneratedColliders.Length; i++)
					{
						RigidColliderCreator.DestroyImmediateWithUndo(autoGeneratedColliders[i]);
					}
				}
				if (hullMapping.targetAutoGeneratedChilds != null)
				{
					foreach (RigidColliderCreatorChild rigidColliderCreatorChild in hullMapping.targetAutoGeneratedChilds)
					{
						GameObject gameObject = rigidColliderCreatorChild.gameObject;
						RigidColliderCreator.DestroyImmediateWithUndo(rigidColliderCreatorChild);
						if (gameObject.transform.childCount == 0 && gameObject.GetComponents<Component>().Length == 1)
						{
							RigidColliderCreator.DestroyImmediateWithUndo(gameObject);
						}
					}
				}
			}
		}

		private static bool IsDeletable(GameObject obj)
		{
			Component[] components = obj.GetComponents<Component>();
			int num = 0;
			foreach (Component component in components)
			{
				if (component is Transform || component is Collider || component is RigidColliderCreator || component is RigidColliderCreatorChild)
				{
					num++;
				}
			}
			return components.Length == num;
		}

		private static void DestroyImmediateWithUndo(Object obj)
		{
			if (obj == null)
			{
				return;
			}
			Object.DestroyImmediate(obj);
		}

		private void CreateHullMapping()
		{
			if (this.hullMapping == null)
			{
				this.hullMapping = new List<HullMapping>();
			}
			for (int i = this.hullMapping.Count - 1; i >= 0; i--)
			{
				HullMapping hullMapping = this.hullMapping[i];
				if (hullMapping == null || hullMapping.sourceHull == null || (hullMapping.generatedCollider == null && hullMapping.targetChild == null))
				{
					this.hullMapping.RemoveAt(i);
				}
			}
			foreach (Hull hull in this.paintingData.hulls)
			{
				if (this.IsMapped(hull))
				{
					Collider collider = RigidColliderCreator.FindExistingCollider(this.hullMapping, hull);
					bool flag = hull.type == HullType.ConvexHull && collider is MeshCollider;
					bool flag2 = hull.type == HullType.Box && collider is BoxCollider;
					bool flag3 = hull.type == HullType.Capsule && collider is CapsuleCollider;
					bool flag4 = hull.type == HullType.Sphere && collider is SphereCollider;
					bool flag5 = hull.type == HullType.Face && collider is MeshCollider;
					bool flag6 = hull.type == HullType.FaceAsBox && collider is BoxCollider;
					bool flag7 = hull.type == HullType.Auto && collider is MeshCollider && hull.autoMeshes != null && hull.autoMeshes.Length != 0;
					bool flag8 = flag || flag2 || flag3 || flag4 || flag5 || flag6 || flag7;
					bool flag9 = collider == null || hull.isChildCollider == (collider.transform.parent == base.transform) || hull.type == HullType.Auto;
					if (!flag8 || !flag9)
					{
						RigidColliderCreator.DestroyImmediateWithUndo(collider);
						this.RemoveMapping(hull);
					}
				}
			}
			List<Hull> list = new List<Hull>();
			List<Collider> list2 = new List<Collider>();
			List<RigidColliderCreatorChild> list3 = new List<RigidColliderCreatorChild>();
			foreach (Hull hull2 in this.paintingData.hulls)
			{
				if (!this.IsMapped(hull2))
				{
					list.Add(hull2);
				}
			}
			foreach (Collider collider2 in this.FindLocal<Collider>())
			{
				if (!this.IsMapped(collider2))
				{
					list2.Add(collider2);
				}
			}
			foreach (RigidColliderCreatorChild rigidColliderCreatorChild in this.FindLocal<RigidColliderCreatorChild>())
			{
				if (!this.IsMapped(rigidColliderCreatorChild))
				{
					list3.Add(rigidColliderCreatorChild);
				}
			}
			for (int j = list.Count - 1; j >= 0; j--)
			{
				Hull hull3 = list[j];
				bool flag10 = false;
				for (int k = list2.Count - 1; k >= 0; k--)
				{
					Collider collider3 = list2[k];
					MeshCollider meshCollider = collider3 as MeshCollider;
					BoxCollider boxCollider = collider3 as BoxCollider;
					CapsuleCollider capsuleCollider = collider3 as CapsuleCollider;
					SphereCollider sphereCollider = collider3 as SphereCollider;
					RigidColliderCreatorChild rigidColliderCreatorChild2 = null;
					if (collider3.transform.parent == base.transform)
					{
						rigidColliderCreatorChild2 = collider3.gameObject.GetComponent<RigidColliderCreatorChild>();
					}
					bool flag11 = hull3.isChildCollider && collider3.transform.parent == base.transform;
					if (rigidColliderCreatorChild2 != null && rigidColliderCreatorChild2.isAutoHull && hull3.type == HullType.Auto && meshCollider != null && hull3.ContainsAutoMesh(meshCollider.sharedMesh))
					{
						HullMapping hullMapping2 = this.FindMapping(hull3);
						if (hullMapping2 == null)
						{
							hullMapping2 = new HullMapping();
							hullMapping2.sourceHull = hull3;
							this.hullMapping.Add(hullMapping2);
						}
						hullMapping2.AddAutoChild(rigidColliderCreatorChild2, collider3 as MeshCollider);
						rigidColliderCreatorChild2.parent = this;
						list2.RemoveAt(k);
						list3.Remove(rigidColliderCreatorChild2);
						flag10 = true;
					}
					else if (flag11)
					{
						bool flag12 = hull3.type == HullType.Box && collider3 is BoxCollider && RigidColliderCreator.Approximately(hull3.collisionBox.collisionBox.center, boxCollider.center) && RigidColliderCreator.Approximately(hull3.collisionBox.collisionBox.size, boxCollider.size);
						bool flag13 = hull3.type == HullType.Sphere && collider3 is SphereCollider && hull3.collisionSphere != null && RigidColliderCreator.Approximately(hull3.collisionSphere.center, sphereCollider.center) && RigidColliderCreator.Approximately(hull3.collisionSphere.radius, sphereCollider.radius);
						bool flag14 = hull3.type == HullType.Capsule && collider3 is CapsuleCollider && RigidColliderCreator.Approximately(hull3.collisionCapsule.capsuleCenter, capsuleCollider.center) && hull3.collisionCapsule.capsuleDirection == (CapsuleAxis)capsuleCollider.direction && RigidColliderCreator.Approximately(hull3.collisionCapsule.capsuleRadius, capsuleCollider.radius) && RigidColliderCreator.Approximately(hull3.collisionCapsule.capsuleHeight, capsuleCollider.radius);
						bool flag15 = hull3.type == HullType.ConvexHull && collider3 is MeshCollider && meshCollider.sharedMesh == hull3.collisionMesh;
						bool flag16 = hull3.type == HullType.Face && collider3 is MeshCollider && meshCollider.sharedMesh == hull3.faceCollisionMesh;
						bool flag17 = hull3.type == HullType.FaceAsBox && collider3 is BoxCollider && RigidColliderCreator.Approximately(hull3.faceBoxCenter, boxCollider.center) && RigidColliderCreator.Approximately(hull3.faceBoxSize, boxCollider.size);
						if (flag12 || flag13 || flag14 || flag15 || flag16 || flag17)
						{
							this.AddMapping(hull3, collider3, rigidColliderCreatorChild2);
							list.RemoveAt(j);
							list2.RemoveAt(k);
							for (int l = 0; l < list3.Count; l++)
							{
								if (list3[l] == rigidColliderCreatorChild2)
								{
									list3.RemoveAt(l);
									break;
								}
							}
							break;
						}
					}
				}
				if (flag10)
				{
					list.RemoveAt(j);
				}
			}
			for (int m = list.Count - 1; m >= 0; m--)
			{
				if (list[m].isChildCollider)
				{
					for (int n = list3.Count - 1; n >= 0; n--)
					{
						RigidColliderCreatorChild child = list3[n];
						HullMapping hullMapping3 = this.FindMapping(child);
						if (hullMapping3 != null && hullMapping3.sourceHull != null)
						{
							if (hullMapping3.generatedCollider == null)
							{
								this.RecreateChildCollider(hullMapping3);
							}
							list.RemoveAt(m);
							list3.RemoveAt(n);
							break;
						}
					}
				}
			}
			for (int num = list.Count - 1; num >= 0; num--)
			{
				Hull hull4 = list[num];
				if (hull4.isChildCollider && hull4.type == HullType.Auto)
				{
					bool flag18 = false;
					for (int num2 = list3.Count - 1; num2 >= 0; num2--)
					{
						RigidColliderCreatorChild rigidColliderCreatorChild3 = list3[num2];
						if (rigidColliderCreatorChild3.isAutoHull && rigidColliderCreatorChild3.gameObject.name.StartsWith(hull4.name))
						{
							HullMapping hullMapping4 = this.FindMapping(hull4);
							if (hullMapping4 == null)
							{
								hullMapping4 = new HullMapping();
								hullMapping4.sourceHull = hull4;
								this.hullMapping.Add(hullMapping4);
							}
							hullMapping4.AddAutoChild(rigidColliderCreatorChild3, null);
							list3.RemoveAt(num2);
							flag18 = true;
						}
					}
					if (flag18)
					{
						list.RemoveAt(num);
					}
				}
			}
			foreach (HullMapping hullMapping5 in this.hullMapping)
			{
				if (hullMapping5.targetChild != null && hullMapping5.generatedCollider == null)
				{
					this.RecreateChildCollider(hullMapping5);
				}
			}
			foreach (HullMapping hullMapping6 in this.hullMapping)
			{
				if (hullMapping6.targetChild == null && hullMapping6.generatedCollider != null && hullMapping6.generatedCollider.transform.parent == base.transform)
				{
					RigidColliderCreatorChild rigidColliderCreatorChild4 = RigidColliderCreator.AddComponent<RigidColliderCreatorChild>(hullMapping6.generatedCollider.gameObject);
					rigidColliderCreatorChild4.parent = this;
					hullMapping6.targetChild = rigidColliderCreatorChild4;
				}
			}
			foreach (Hull hull5 in list)
			{
				if (hull5.type == HullType.Box)
				{
					this.CreateCollider<BoxCollider>(hull5);
				}
				else if (hull5.type == HullType.Sphere)
				{
					this.CreateCollider<SphereCollider>(hull5);
				}
				else if (hull5.type == HullType.ConvexHull)
				{
					this.CreateCollider<MeshCollider>(hull5);
				}
				else if (hull5.type == HullType.Face)
				{
					this.CreateCollider<MeshCollider>(hull5);
				}
				else if (hull5.type == HullType.FaceAsBox)
				{
					this.CreateCollider<BoxCollider>(hull5);
				}
				else if (hull5.type == HullType.Capsule)
				{
					this.CreateCollider<CapsuleCollider>(hull5);
				}
			}
			foreach (Collider collider4 in list2)
			{
				if (!(collider4 == null))
				{
					if (collider4.gameObject == base.gameObject)
					{
						RigidColliderCreator.DestroyImmediateWithUndo(collider4);
					}
					else
					{
						GameObject gameObject = collider4.gameObject;
						RigidColliderCreator.DestroyImmediateWithUndo(collider4);
						RigidColliderCreator.DestroyImmediateWithUndo(gameObject.GetComponent<RigidColliderCreatorChild>());
						if (RigidColliderCreator.IsDeletable(gameObject))
						{
							RigidColliderCreator.DestroyImmediateWithUndo(gameObject);
						}
					}
				}
			}
			foreach (RigidColliderCreatorChild rigidColliderCreatorChild5 in list3)
			{
				if (!(rigidColliderCreatorChild5 == null))
				{
					GameObject gameObject2 = rigidColliderCreatorChild5.gameObject;
					RigidColliderCreator.DestroyImmediateWithUndo(rigidColliderCreatorChild5);
					RigidColliderCreator.DestroyImmediateWithUndo(gameObject2.GetComponent<Collider>());
					if (RigidColliderCreator.IsDeletable(gameObject2))
					{
						RigidColliderCreator.DestroyImmediateWithUndo(gameObject2);
					}
				}
			}
		}

		private static bool Approximately(Vector3 lhs, Vector3 rhs)
		{
			return Mathf.Approximately(lhs.x, rhs.x) && Mathf.Approximately(lhs.y, rhs.y) && Mathf.Approximately(lhs.z, rhs.z);
		}

		private static bool Approximately(float lhs, float rhs)
		{
			return Mathf.Approximately(lhs, rhs);
		}

		private void CreateCollider<T>(Hull sourceHull) where T : Collider
		{
			if (sourceHull.isChildCollider)
			{
				GameObject gameObject = RigidColliderCreator.CreateGameObject(sourceHull.name);
				gameObject.transform.SetParent(base.transform, false);
				gameObject.transform.localPosition = Vector3.zero;
				gameObject.transform.localRotation = Quaternion.identity;
				gameObject.transform.localScale = Vector3.one;
				RigidColliderCreatorChild rigidColliderCreatorChild = RigidColliderCreator.AddComponent<RigidColliderCreatorChild>(gameObject);
				rigidColliderCreatorChild.parent = this;
				T t = RigidColliderCreator.AddComponent<T>(gameObject);
				this.AddMapping(sourceHull, t, rigidColliderCreatorChild);
				return;
			}
			T t2 = RigidColliderCreator.AddComponent<T>(base.gameObject);
			this.AddMapping(sourceHull, t2, null);
		}

		private void RecreateChildCollider(HullMapping mapping)
		{
			if (mapping == null || mapping.sourceHull == null || !mapping.sourceHull.isChildCollider)
			{
				return;
			}
			if (mapping.sourceHull.type == HullType.Box)
			{
				this.RecreateChildCollider<BoxCollider>(mapping);
				return;
			}
			if (mapping.sourceHull.type == HullType.Sphere)
			{
				this.RecreateChildCollider<SphereCollider>(mapping);
				return;
			}
			if (mapping.sourceHull.type == HullType.ConvexHull)
			{
				this.RecreateChildCollider<MeshCollider>(mapping);
				return;
			}
			if (mapping.sourceHull.type == HullType.Face)
			{
				this.RecreateChildCollider<MeshCollider>(mapping);
				return;
			}
			if (mapping.sourceHull.type == HullType.FaceAsBox)
			{
				this.RecreateChildCollider<BoxCollider>(mapping);
				return;
			}
			if (mapping.sourceHull.type == HullType.Capsule)
			{
				this.RecreateChildCollider<CapsuleCollider>(mapping);
			}
		}

		private void RecreateChildCollider<T>(HullMapping mapping) where T : Collider
		{
			if (mapping.sourceHull == null || !mapping.sourceHull.isChildCollider)
			{
				return;
			}
			T t = RigidColliderCreator.AddComponent<T>(mapping.targetChild.gameObject);
			mapping.generatedCollider = t;
		}

		private void UpdateCollider(Hull hull)
		{
			Collider collider = null;
			if (hull.type == HullType.Box)
			{
				BoxCollider boxCollider = RigidColliderCreator.FindExistingCollider(this.hullMapping, hull) as BoxCollider;
				boxCollider.center = hull.collisionBox.collisionBox.center;
				boxCollider.size = hull.collisionBox.collisionBox.size + (hull.enableInflation ? (Vector3.one * hull.inflationAmount) : Vector3.zero);
				if (hull.isChildCollider)
				{
					boxCollider.transform.localPosition = hull.collisionBox.boxPosition;
					boxCollider.transform.localRotation = hull.collisionBox.boxRotation;
				}
				collider = boxCollider;
			}
			else if (hull.type == HullType.Sphere)
			{
				SphereCollider sphereCollider = RigidColliderCreator.FindExistingCollider(this.hullMapping, hull) as SphereCollider;
				sphereCollider.radius = hull.collisionSphere.radius + (hull.enableInflation ? hull.inflationAmount : 0f);
				if (hull.isChildCollider)
				{
					sphereCollider.transform.localPosition = hull.collisionSphere.center;
				}
				else
				{
					sphereCollider.center = hull.collisionSphere.center;
				}
				collider = sphereCollider;
			}
			else if (hull.type == HullType.Capsule)
			{
				CapsuleCollider capsuleCollider = RigidColliderCreator.FindExistingCollider(this.hullMapping, hull) as CapsuleCollider;
				capsuleCollider.center = hull.collisionCapsule.capsuleCenter;
				capsuleCollider.direction = (int)hull.collisionCapsule.capsuleDirection;
				capsuleCollider.radius = hull.collisionCapsule.capsuleRadius;
				capsuleCollider.height = hull.collisionCapsule.capsuleHeight;
				if (hull.isChildCollider)
				{
					capsuleCollider.transform.localPosition = hull.collisionCapsule.capsulePosition;
					capsuleCollider.transform.localRotation = hull.collisionCapsule.capsuleRotation;
				}
				collider = capsuleCollider;
			}
			else if (hull.type == HullType.ConvexHull)
			{
				MeshCollider meshCollider = RigidColliderCreator.FindExistingCollider(this.hullMapping, hull) as MeshCollider;
				meshCollider.sharedMesh = hull.collisionMesh;
				meshCollider.convex = true;
				meshCollider.cookingOptions &= ~MeshColliderCookingOptions.EnableMeshCleaning;
				collider = meshCollider;
			}
			else if (hull.type == HullType.Face)
			{
				MeshCollider meshCollider2 = RigidColliderCreator.FindExistingCollider(this.hullMapping, hull) as MeshCollider;
				meshCollider2.sharedMesh = hull.faceCollisionMesh;
				meshCollider2.convex = true;
				collider = meshCollider2;
			}
			else if (hull.type == HullType.FaceAsBox)
			{
				BoxCollider boxCollider2 = RigidColliderCreator.FindExistingCollider(this.hullMapping, hull) as BoxCollider;
				boxCollider2.size = hull.faceBoxSize + (hull.enableInflation ? (Vector3.one * hull.inflationAmount) : Vector3.zero);
				if (hull.isChildCollider)
				{
					boxCollider2.transform.localPosition = hull.faceBoxCenter;
					boxCollider2.transform.localRotation = hull.faceAsBoxRotation;
				}
				else
				{
					boxCollider2.center = hull.faceBoxCenter;
				}
				collider = boxCollider2;
			}
			else
			{
				HullType type = hull.type;
			}
			if (collider != null)
			{
				collider.material = hull.material;
				collider.isTrigger = hull.isTrigger;
				if (hull.isChildCollider)
				{
					collider.gameObject.name = hull.name;
				}
			}
		}

		public void SetAllTypes(HullType newType)
		{
			foreach (Hull hull in this.paintingData.hulls)
			{
				hull.type = newType;
			}
		}

		public void SetAllMaterials(PhysicsMaterial newMaterial)
		{
			foreach (Hull hull in this.paintingData.hulls)
			{
				hull.material = newMaterial;
			}
		}

		public void SetAllAsChild(bool isChild)
		{
			foreach (Hull hull in this.paintingData.hulls)
			{
				hull.isChildCollider = isChild;
			}
		}

		public void SetAllAsTrigger(bool isTrigger)
		{
			foreach (Hull hull in this.paintingData.hulls)
			{
				hull.isTrigger = isTrigger;
			}
		}

		private List<T> FindLocal<T>() where T : Component
		{
			List<T> list = new List<T>();
			list.AddRange(base.gameObject.GetComponents<T>());
			for (int i = 0; i < base.transform.childCount; i++)
			{
				list.AddRange(base.transform.GetChild(i).GetComponents<T>());
			}
			return list;
		}

		private bool IsMapped(Hull hull)
		{
			if (this.hullMapping == null)
			{
				return false;
			}
			using (List<HullMapping>.Enumerator enumerator = this.hullMapping.GetEnumerator())
			{
				while (enumerator.MoveNext())
				{
					if (enumerator.Current.sourceHull == hull)
					{
						return true;
					}
				}
			}
			return false;
		}

		private bool IsMapped(Collider col)
		{
			if (this.hullMapping == null)
			{
				return false;
			}
			using (List<HullMapping>.Enumerator enumerator = this.hullMapping.GetEnumerator())
			{
				while (enumerator.MoveNext())
				{
					if (enumerator.Current.generatedCollider == col)
					{
						return true;
					}
				}
			}
			return false;
		}

		private bool IsMapped(RigidColliderCreatorChild child)
		{
			if (this.hullMapping == null)
			{
				return false;
			}
			using (List<HullMapping>.Enumerator enumerator = this.hullMapping.GetEnumerator())
			{
				while (enumerator.MoveNext())
				{
					if (enumerator.Current.targetChild == child)
					{
						return true;
					}
				}
			}
			return false;
		}

		private void AddMapping(Hull hull, Collider col, RigidColliderCreatorChild painterChild)
		{
			HullMapping item = new HullMapping
			{
				sourceHull = hull,
				generatedCollider = col,
				targetChild = painterChild
			};
			this.hullMapping.Add(item);
		}

		private void RemoveMapping(Hull hull)
		{
			for (int i = 0; i < this.hullMapping.Count; i++)
			{
				if (this.hullMapping[i].sourceHull == hull)
				{
					this.hullMapping.RemoveAt(i);
					return;
				}
			}
		}

		private HullMapping FindMapping(RigidColliderCreatorChild child)
		{
			if (this.hullMapping == null)
			{
				return null;
			}
			foreach (HullMapping hullMapping in this.hullMapping)
			{
				if (hullMapping.targetChild == child)
				{
					return hullMapping;
				}
			}
			return null;
		}

		private HullMapping FindMapping(Hull hull)
		{
			if (this.hullMapping == null)
			{
				return null;
			}
			foreach (HullMapping hullMapping in this.hullMapping)
			{
				if (hullMapping.sourceHull == hull)
				{
					return hullMapping;
				}
			}
			return null;
		}

		public Hull FindSourceHull(RigidColliderCreatorChild child)
		{
			if (this.hullMapping == null)
			{
				return null;
			}
			foreach (HullMapping hullMapping in this.hullMapping)
			{
				if (hullMapping.targetChild == child)
				{
					return hullMapping.sourceHull;
				}
				if (hullMapping.targetAutoGeneratedChilds != null)
				{
					RigidColliderCreatorChild[] targetAutoGeneratedChilds = hullMapping.targetAutoGeneratedChilds;
					for (int i = 0; i < targetAutoGeneratedChilds.Length; i++)
					{
						if (targetAutoGeneratedChilds[i] == child)
						{
							return hullMapping.sourceHull;
						}
					}
				}
			}
			return null;
		}

		private static Collider FindExistingCollider(List<HullMapping> mappings, Hull hull)
		{
			foreach (HullMapping hullMapping in mappings)
			{
				if (hullMapping.sourceHull == hull)
				{
					return hullMapping.generatedCollider;
				}
			}
			return null;
		}

		private void CreateAutoHulls(Hull hull, Mesh[] autoHulls)
		{
			if (hull.type != HullType.Auto)
			{
				return;
			}
			HullMapping hullMapping = this.FindMapping(hull);
			if (hullMapping == null)
			{
				hullMapping = new HullMapping();
				hullMapping.sourceHull = hull;
				this.hullMapping.Add(hullMapping);
			}
			Mesh[] autoMeshes = hull.autoMeshes;
			List<MeshCollider> list = new List<MeshCollider>();
			if (hullMapping.targetAutoGeneratedChilds != null)
			{
				for (int i = 0; i < hullMapping.targetAutoGeneratedChilds.Length; i++)
				{
					if (hullMapping.autoGeneratedColliders != null && i < hullMapping.autoGeneratedColliders.Length)
					{
						list.Add(hullMapping.autoGeneratedColliders[i]);
					}
					else
					{
						MeshCollider meshCollider = hullMapping.targetAutoGeneratedChilds[i].gameObject.AddComponent<MeshCollider>();
						meshCollider.convex = true;
						list.Add(meshCollider);
					}
				}
			}
			for (int j = list.Count - 1; j >= 0; j--)
			{
				bool flag = list[j].transform != base.transform;
				if (flag != base.transform && hull.isChildCollider)
				{
					if (flag)
					{
						Object.DestroyImmediate(list[j].gameObject);
					}
					else
					{
						Object.DestroyImmediate(list[j]);
					}
					list.RemoveAt(j);
				}
			}
			for (int k = 0; k < autoMeshes.Length; k++)
			{
				Mesh sharedMesh = autoMeshes[k];
				MeshCollider meshCollider2;
				if (k < list.Count)
				{
					meshCollider2 = list[k];
				}
				else if (hull.isChildCollider)
				{
					GameObject gameObject = RigidColliderCreator.CreateGameObject("New child");
					gameObject.transform.SetParent(base.transform, false);
					RigidColliderCreatorChild rigidColliderCreatorChild = gameObject.AddComponent<RigidColliderCreatorChild>();
					rigidColliderCreatorChild.parent = this;
					rigidColliderCreatorChild.isAutoHull = true;
					meshCollider2 = gameObject.AddComponent<MeshCollider>();
					list.Add(meshCollider2);
				}
				else
				{
					meshCollider2 = base.gameObject.AddComponent<MeshCollider>();
					list.Add(meshCollider2);
				}
				meshCollider2.sharedMesh = sharedMesh;
				meshCollider2.convex = true;
				meshCollider2.isTrigger = hull.isTrigger;
				meshCollider2.material = hull.material;
			}
			if (hull.isChildCollider)
			{
				for (int l = 0; l < list.Count; l++)
				{
					list[l].gameObject.name = string.Format("{0}.{1}", hull.name, l + 1);
				}
			}
			List<RigidColliderCreatorChild> list2 = new List<RigidColliderCreatorChild>();
			foreach (MeshCollider meshCollider3 in list)
			{
				list2.Add(meshCollider3.GetComponent<RigidColliderCreatorChild>());
			}
			hullMapping.autoGeneratedColliders = list.ToArray();
			hullMapping.targetAutoGeneratedChilds = list2.ToArray();
		}

		private static GameObject CreateGameObject(string goName)
		{
			return new GameObject(goName);
		}

		private static T AddComponent<T>(GameObject targetObj) where T : Component
		{
			return targetObj.AddComponent<T>();
		}

		private void OnDrawGizmos()
		{
		}

		public PaintingData paintingData;

		public HullData hullData;

		private List<HullMapping> hullMapping;

		private Mesh debugMesh;
	}
}
