using System;
using Oculus.Interaction.Input;
using UnityEngine;

namespace Oculus.Interaction.Locomotion
{
	public class LocomotionTurnerInteractorVisual : MonoBehaviour
	{
		private IAxis1D Progress { get; set; }

		public float VerticalOffset
		{
			get
			{
				return this._verticalOffset;
			}
			set
			{
				this._verticalOffset = value;
			}
		}

		protected virtual void Awake()
		{
			this.Progress = (this._progress as IAxis1D);
		}

		protected virtual void Start()
		{
			this.BeginStart(ref this._started, null);
			if (this._root == null)
			{
				this._root = base.transform;
			}
			this.EndStart(ref this._started);
		}

		protected virtual void OnEnable()
		{
			if (this._started && this._turner != null)
			{
				this._turner.WhenStateChanged += this.HandleTurnerStateChanged;
				this._turner.WhenPreprocessed += this.HandleTurnerPostprocessed;
			}
		}

		protected virtual void OnDisable()
		{
			if (this._started && this._turner != null)
			{
				this._turner.WhenStateChanged -= this.HandleTurnerStateChanged;
				this._turner.WhenPreprocessed -= this.HandleTurnerPostprocessed;
			}
		}

		private void HandleTurnerStateChanged(InteractorStateChangeArgs stateArgs)
		{
			if (stateArgs.NewState == InteractorState.Disabled)
			{
				this._visuals.DisableVisuals();
			}
		}

		private void HandleTurnerPostprocessed()
		{
			if (this._turner != null && this._turner.State == InteractorState.Disabled)
			{
				return;
			}
			this.UpdatePose(this._turner.MidPoint);
			this._visuals.Progress = this.Progress.Value();
			this._visuals.Value = this._turner.Value();
			this._visuals.FollowArrow = (this._broadcaster == null || this._broadcaster.TurnMethod == TurnerEventBroadcaster.TurnMode.Snap);
			this._visuals.HighLight = (this._turner.State == InteractorState.Select);
			this._visuals.UpdateVisual();
		}

		private void UpdatePose(Pose origin)
		{
			Vector3 vector = origin.forward;
			if (this._lookAt != null)
			{
				vector = Vector3.ProjectOnPlane(origin.position - this._lookAt.position, origin.up).normalized;
			}
			Vector3 position = origin.position - vector * this._visuals.Radius + origin.up * this._verticalOffset;
			Quaternion rotation = Quaternion.LookRotation(vector, origin.up);
			this._root.SetPositionAndRotation(position, rotation);
		}

		public void InjectAllLocomotionTurnerInteractorArrowsVisual(LocomotionTurnerInteractor turner, TurnArrowVisuals visuals)
		{
			this.InjectTurner(turner);
			this.InjectVisuals(visuals);
		}

		public void InjectTurner(LocomotionTurnerInteractor turner)
		{
			this._turner = turner;
		}

		public void InjectOptionalRoot(Transform root)
		{
			this._root = root;
		}

		public void InjectVisuals(TurnArrowVisuals visuals)
		{
			this._visuals = visuals;
		}

		public void InjectOptionalLookAt(Transform lookAt)
		{
			this._lookAt = lookAt;
		}

		public void InjectOptionalProgress(IAxis1D progress)
		{
			this._progress = (progress as Object);
			this.Progress = progress;
		}

		[SerializeField]
		private LocomotionTurnerInteractor _turner;

		[SerializeField]
		[Optional]
		private TurnerEventBroadcaster _broadcaster;

		[SerializeField]
		[Optional]
		private Transform _lookAt;

		[SerializeField]
		[Optional(OptionalAttribute.Flag.AutoGenerated)]
		private Transform _root;

		[SerializeField]
		private TurnArrowVisuals _visuals;

		[SerializeField]
		[Interface(typeof(IAxis1D), new Type[]
		{

		})]
		[Optional]
		private Object _progress;

		[SerializeField]
		private float _verticalOffset = 0.02f;

		protected bool _started;
	}
}
